# Site settings
name: 巴塞罗那的余晖
location: China
company: None
position: Java开发工程师、Android工程师
github: https://github.com/paul623
facebook: https://www.facebook.com/
phone: 17851559306
email: zhubaoluo@outlook.com

baseurl: "/paul623.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

